//! Independent, can-disagree oracle for the strike-axis leaf
//! (CRYPTO-SURFACE-LEAF-SPEC §4 / §5.3). Five legs; none reuses production
//! assembly; at least two can disagree with the production fitter by
//! construction (the FRTB-0.75ρ lesson: every reference formula re-derived from
//! the published source, never read back from production).
//!
//! * **O1 — injected ground truth**: synthetic grids generated by an in-test
//!   re-typed raw-SVI formula at known arbitrage-free parameters; the fitter
//!   sees only `(K_i, σ_i)`.
//! * **O2 — independent linear algebra**: the inner normal equations re-derived
//!   from scratch at the *fitted* `(m, σ)` and solved by **Cramer's rule**
//!   (independent of the production Gaussian elimination).
//! * **O3 — density law re-derivation**: Breeden–Litzenberger second-difference
//!   density from an in-test re-typed undiscounted Black forward call,
//!   cross-checked against the closed-form Durrleman `g ≥ 0` claim.
//! * **O5 — cross-path can-disagree canary**: the FX delta path and the strike
//!   path agree on exact-SVI data and *demonstrably disagree* (with the FX path
//!   bit-frozen) when only the strike inputs move.
//! * **Convention pins**: the published Deribit venue identities the leaf's
//!   axis/`t` semantics rest on (deribit.com/kb; values stay ENV per the W3 §9
//!   honest boundary).
//!
//! (O4 — carry-seam byte identity — lives with the unit tests in
//! `strike_quotes.rs::tests::context_forward_is_carry_seam_bits`.)
//!
//! Plus the 24×7 term-structure leg: monotone-θ pillars assemble into an
//! arbitrage-free surface on the identity clock; a decreasing-θ pair is flagged
//! by the calendar increment — assemble, report, never silently repair.

use celnet_conventions::resolve;
use celnet_core::math::norm_cdf;
use celnet_crypto_vanilla::{deribit, funding_carry};
use celnet_surface::{
    CalibratedSmile, MarketContext, MarketQuotes, ParametricSlice, SmileModel, StrikeQuote,
    StrikeQuoteSlice, StrikeSliceContext, build_model_smile, fit_strike_slice, strike_surface,
};
use celnet_types::{Carry, CcyPair, Tenor};

// =========================================================================
// In-test reference formulas (re-typed from the published sources — NOT calls
// into production code).
// =========================================================================

/// Raw-SVI total variance, re-typed from Gatheral (2004) / Gatheral & Jacquier
/// (2014) eq. 3.1.
fn svi_w_reference(k: f64, a: f64, b: f64, rho: f64, m: f64, sigma: f64) -> f64 {
    a + b * (rho * (k - m) + ((k - m) * (k - m) + sigma * sigma).sqrt())
}

/// Undiscounted Black forward call, re-typed from the published formula
/// (the `surface_properties.rs` oracle pattern — independent of
/// `celnet_surface::arbitrage`).
fn black_call(forward: f64, strike: f64, vol: f64, t: f64) -> f64 {
    let st = vol * t.sqrt();
    let d1 = ((forward / strike).ln() + 0.5 * st * st) / st;
    let d2 = d1 - st;
    forward * norm_cdf(d1) - strike * norm_cdf(d2)
}

/// A strike grid of `n` log-spaced strikes spanning `k ∈ ±k_span` around the
/// context's carry-seam forward, with vols from the reference SVI formula.
fn reference_grid(
    ctx: &StrikeSliceContext,
    truth: (f64, f64, f64, f64, f64),
    k_span: f64,
    n: usize,
) -> StrikeQuoteSlice {
    let (a, b, rho, m, sigma) = truth;
    let f = ctx.forward();
    StrikeQuoteSlice::new(
        (0..n)
            .map(|i| {
                let k = -k_span + 2.0 * k_span * (i as f64) / (n - 1) as f64;
                let w = svi_w_reference(k, a, b, rho, m, sigma);
                StrikeQuote {
                    strike: f * k.exp(),
                    vol: (w / ctx.t).sqrt(),
                }
            })
            .collect(),
    )
}

/// The ETH-scale fixture: negative net carry (`funding > r` lowers the
/// forward below spot), exact arbitrage-free raw-SVI ground truth.
fn eth_fixture() -> (
    StrikeSliceContext,
    (f64, f64, f64, f64, f64),
    StrikeQuoteSlice,
) {
    let ctx = StrikeSliceContext::new(3_000.0, funding_carry(0.04, 0.06), 0.5);
    let truth = (0.02, 0.12, -0.35, -0.01, 0.2);
    let quotes = reference_grid(&ctx, truth, 0.5, 11);
    (ctx, truth, quotes)
}

// =========================================================================
// O1 — injected ground truth (ETH scale; the BTC-scale leg lives in the unit
// tests).
// =========================================================================

/// The fitter recovers an exact arbitrage-free truth it never saw the
/// parameters of — on-grid to half a micro-vol, off-grid in total variance,
/// and in the parameters themselves.
#[test]
fn eth_exact_svi_grid_round_trips() {
    let (ctx, truth, quotes) = eth_fixture();
    let (a, b, rho, m, sigma) = truth;
    let fit = fit_strike_slice(&ctx, &quotes).unwrap();

    assert!(
        fit.max_vol_error <= 5e-7,
        "on-grid max vol error {} must be ≤ 5e-7",
        fit.max_vol_error
    );
    for j in 0..=40 {
        let k = -0.6 + 1.2 * f64::from(j) / 40.0;
        let w_fit = fit.slice.total_variance(k);
        let w_truth = svi_w_reference(k, a, b, rho, m, sigma);
        assert!(
            (w_fit - w_truth).abs() <= 1e-7,
            "off-grid w at k={k}: fit {w_fit} vs truth {w_truth}"
        );
    }
    assert!((fit.slice.b - b).abs() / b <= 1e-4);
    assert!((fit.slice.sigma - sigma).abs() / sigma <= 1e-4);
    assert!((fit.slice.rho - rho).abs() <= 1e-4);
    assert!((fit.slice.m - m).abs() <= 1e-4);
    assert!((fit.slice.a - a).abs() <= 1e-6);
}

// =========================================================================
// O2 — independent linear algebra (Cramer's rule).
// =========================================================================

/// Solve a 3×3 system by Cramer's rule (cofactor determinants) — a genuinely
/// different algorithm from the production partial-pivoting Gaussian
/// elimination; a transposed/sign-flipped normal-equation assembly in either
/// implementation breaks the agreement.
fn cramer3(m: &[[f64; 3]; 3], r: &[f64; 3]) -> [f64; 3] {
    let det = |x: &[[f64; 3]; 3]| -> f64 {
        x[0][0] * (x[1][1] * x[2][2] - x[1][2] * x[2][1])
            - x[0][1] * (x[1][0] * x[2][2] - x[1][2] * x[2][0])
            + x[0][2] * (x[1][0] * x[2][1] - x[1][1] * x[2][0])
    };
    let d = det(m);
    assert!(
        d.abs() > 1e-12,
        "normal equations must be non-singular: {d}"
    );
    let mut out = [0.0_f64; 3];
    for (j, slot) in out.iter_mut().enumerate() {
        let mut mj = *m;
        for i in 0..3 {
            mj[i][j] = r[i];
        }
        *slot = det(&mj) / d;
    }
    out
}

/// At the *fitted* `(m, σ)` (read from the returned slice's public fields) the
/// test re-derives the inner 3×3 normal equations from scratch and solves them
/// by Cramer's rule; the production-implied `(a, c = bρσ, d = bσ)` must match.
#[test]
fn inner_linear_solution_matches_cramer_rederivation() {
    let (ctx, _, quotes) = eth_fixture();
    let fit = fit_strike_slice(&ctx, &quotes).unwrap();
    let (m, sigma) = (fit.slice.m, fit.slice.sigma);

    // Re-derive anchors and the normal equations from scratch (in-test ln/σ²t).
    let f = ctx.forward();
    let n = quotes.quotes().len() as f64;
    let (mut sy, mut sz, mut syy, mut syz, mut szz) = (0.0_f64, 0.0, 0.0, 0.0, 0.0);
    let (mut sw, mut syw, mut szw) = (0.0_f64, 0.0, 0.0);
    for q in quotes.quotes() {
        let k = (q.strike / f).ln();
        let w = q.vol * q.vol * ctx.t;
        let y = (k - m) / sigma;
        let z = (y * y + 1.0).sqrt();
        sy += y;
        sz += z;
        syy += y * y;
        syz += y * z;
        szz += z * z;
        sw += w;
        syw += y * w;
        szw += z * w;
    }
    let lhs = [[n, sy, sz], [sy, syy, syz], [sz, syz, szz]];
    let [a_ref, c_ref, d_ref] = cramer3(&lhs, &[sw, syw, szw]);

    // Production-implied inner solution from the public slice parameters.
    let a_prod = fit.slice.a;
    let c_prod = fit.slice.b * fit.slice.rho * fit.slice.sigma;
    let d_prod = fit.slice.b * fit.slice.sigma;

    assert!(
        (a_prod - a_ref).abs() <= 1e-9,
        "a: production {a_prod} vs Cramer {a_ref}"
    );
    assert!(
        (c_prod - c_ref).abs() <= 1e-9,
        "c: production {c_prod} vs Cramer {c_ref}"
    );
    assert!(
        (d_prod - d_ref).abs() <= 1e-9,
        "d: production {d_prod} vs Cramer {d_ref}"
    );
}

// =========================================================================
// O3 — density law re-derivation (Breeden–Litzenberger vs Durrleman).
// =========================================================================

/// The risk-neutral density of the fitted slice — the second strike-difference
/// of the in-test undiscounted Black forward call — is non-negative across the
/// wing span, and the *independent* closed-form Durrleman notion agrees: two
/// different no-arbitrage laws, one verdict.
#[test]
fn fd_density_nonnegative_and_agrees_with_durrleman() {
    let (ctx, _, quotes) = eth_fixture();
    let fit = fit_strike_slice(&ctx, &quotes).unwrap();
    let slice = fit.slice;
    let f = ctx.forward();
    let t = ctx.t;

    let atm_vol = slice.vol_at(f);
    let span = 2.0 * (atm_vol * t.sqrt()).max(0.6);
    let h = 1e-3 * f;
    for j in 0..=48 {
        let k = -span + 2.0 * span * f64::from(j) / 48.0;
        let strike = f * k.exp();
        let c = |kk: f64| black_call(f, kk, slice.vol_at(kk), t);
        let density = (c(strike - h) - 2.0 * c(strike) + c(strike + h)) / (h * h);
        assert!(
            density >= -1e-7,
            "Breeden–Litzenberger density {density} < 0 at k={k}"
        );
    }
    assert!(
        slice.is_butterfly_free(span, 1e-6),
        "Durrleman g must agree the slice is butterfly-free; min g = {}",
        slice.min_butterfly_density_factor(span, 4096)
    );
}

// =========================================================================
// O5 — cross-path can-disagree canary vs the FX delta path.
// =========================================================================

/// The FX EURUSD fixture (pronounced skew, five-point broker quotes) and its
/// calibrated parametric slice.
fn fx_parametric_slice() -> (MarketContext, MarketQuotes, ParametricSlice) {
    let conv = resolve(CcyPair::parse("EURUSD").unwrap(), Tenor::Years(1)).record;
    let ctx = MarketContext::new(
        1.10,
        Carry::FxRates {
            r_dom: 0.02,
            r_for: 0.01,
        },
        1.0,
        conv,
    );
    let quotes = MarketQuotes::five_point(0.11, -0.02, 0.006, -0.035, 0.012);
    let CalibratedSmile::Parametric(slice) =
        build_model_smile(SmileModel::Parametric, &ctx, &quotes).unwrap()
    else {
        unreachable!("Parametric selection returns the Parametric variant")
    };
    (ctx, quotes, slice)
}

/// Sample the FX slice at 9 strikes spanning `[0.85F, 1.20F]` as a strike grid.
fn fx_sampled_strike_grid(fx: &ParametricSlice) -> StrikeQuoteSlice {
    let f = fx.forward;
    StrikeQuoteSlice::new(
        (0..9)
            .map(|i| {
                let strike = f * (0.85 + 0.35 * f64::from(i) / 8.0);
                StrikeQuote {
                    strike,
                    vol: fx.vol_at(strike),
                }
            })
            .collect(),
    )
}

/// (i) Agreement when they must agree: the strike fit of an exact FX-calibrated
/// SVI slice recovers it across `k ∈ [−0.25, 0.25]`. (ii) Disagreement when
/// they must disagree: bumping ONE strike quote moves the strike-path fit while
/// the FX-path slice (unchanged broker quotes) stays **bit-identical** — the
/// two front-ends are driven by disjoint inputs.
#[test]
fn cross_path_canary_agrees_then_disagrees() {
    let (fx_ctx, fx_quotes, fx_slice) = fx_parametric_slice();
    // The strike front-end accepts the SAME FxRates carry: the leaf is
    // basis-defined, not asset-defined.
    let s_ctx = StrikeSliceContext::new(fx_ctx.spot, fx_ctx.carry, fx_ctx.t);
    assert_eq!(s_ctx.forward().to_bits(), fx_ctx.forward().to_bits());

    let grid = fx_sampled_strike_grid(&fx_slice);
    let fit = fit_strike_slice(&s_ctx, &grid).unwrap();

    // (i) Agreement across k ∈ [−0.25, 0.25].
    for j in 0..=20 {
        let k = -0.25 + 0.5 * f64::from(j) / 20.0;
        let w_strike = fit.slice.total_variance(k);
        let w_fx = fx_slice.total_variance(k);
        assert!(
            (w_strike - w_fx).abs() <= 1e-7,
            "paths must agree on exact data at k={k}: strike {w_strike} vs fx {w_fx}"
        );
    }

    // (ii) Disagreement: bump the middle strike quote by one vol point.
    let mut bumped: Vec<StrikeQuote> = grid.quotes().to_vec();
    bumped[4].vol += 0.01;
    let k4 = (bumped[4].strike / s_ctx.forward()).ln();
    let bumped_fit = fit_strike_slice(&s_ctx, &StrikeQuoteSlice::new(bumped)).unwrap();
    let moved = (bumped_fit.slice.total_variance(k4) - fit.slice.total_variance(k4)).abs();
    assert!(
        moved > 1e-4,
        "strike-path w at the bumped quote must move (Δw = {moved})"
    );

    // The FX path, recalibrated from its UNCHANGED broker quotes, is
    // bit-identical — the strike path cannot be secretly feeding it.
    let CalibratedSmile::Parametric(fx_again) =
        build_model_smile(SmileModel::Parametric, &fx_ctx, &fx_quotes).unwrap()
    else {
        unreachable!()
    };
    for (x, y) in [
        (fx_again.a, fx_slice.a),
        (fx_again.b, fx_slice.b),
        (fx_again.rho, fx_slice.rho),
        (fx_again.m, fx_slice.m),
        (fx_again.sigma, fx_slice.sigma),
        (fx_again.forward, fx_slice.forward),
        (fx_again.t, fx_slice.t),
    ] {
        assert_eq!(x.to_bits(), y.to_bits(), "FX slice must stay bit-frozen");
    }
}

// =========================================================================
// Convention pins (published venue identities; live values stay ENV).
// =========================================================================

/// The Deribit venue identities the leaf's `t`/axis semantics rest on
/// (deribit.com/kb "Option specification" / "Expiration"): European exercise,
/// inverse coin settlement, the 08:00 UTC expiry cut. Identity pins only — the
/// quote/fixing VALUES remain deploy-validated ENV (W3 §9 honest boundary).
#[test]
fn venue_convention_identities_are_pinned() {
    assert_eq!(deribit::EXPIRY_CUT_UTC_SECONDS, 28_800, "08:00 UTC cut");
    assert_eq!(deribit::STYLE_EUROPEAN, "European");
    // Settlement identity pinned via the derived label (the crypto leaf's own
    // pin pattern; a plain assert on the const is a clippy constant-assertion).
    let settlement = if deribit::SETTLEMENT_IS_INVERSE_COIN {
        "inverse-coin"
    } else {
        "linear-usd"
    };
    assert_eq!(settlement, "inverse-coin");
}

// =========================================================================
// The 24×7 term-structure leg (identity clock).
// =========================================================================

/// Two exact-SVI expiries with monotone total variance assemble through
/// `strike_surface` into an arbitrage-free 24×7 surface (per-slice butterfly /
/// vertical + cross-expiry calendar all clean).
#[test]
fn monotone_pillars_make_an_arbitrage_free_24x7_surface() {
    let t1 = 7.0 / 365.0;
    let t2 = 28.0 / 365.0;
    let ctx1 = StrikeSliceContext::new(3_000.0, funding_carry(0.04, 0.01), t1);
    let ctx2 = StrikeSliceContext::new(3_000.0, funding_carry(0.04, 0.01), t2);
    // truth2 = 4 × truth1 in (a, b) ⇒ w₂(k) = 4·w₁(k): strictly increasing
    // total variance at every strike (the funding-carry forward drift between
    // the expiries is tiny against the 3× variance margin).
    let truth1 = (0.003, 0.02, -0.3, 0.01, 0.18);
    let truth2 = (0.012, 0.08, -0.3, 0.01, 0.18);
    let q1 = reference_grid(&ctx1, truth1, 0.4, 11);
    let q2 = reference_grid(&ctx2, truth2, 0.4, 11);

    let surface = strike_surface(&[(ctx1, q1), (ctx2, q2)], 1e-4).unwrap();
    assert_eq!(surface.model(), SmileModel::Parametric);
    let report = surface.arbitrage_report(0.5, 81, 8, 1e-3);
    assert!(
        report.is_arbitrage_free(1e-4),
        "monotone 24×7 surface must be arbitrage-free: {report:?}"
    );
}

/// A decreasing-total-variance pair still assembles (each slice individually
/// reproduces its quotes) but the calendar increment FLAGS the arbitrage —
/// assemble, report, let the publish gate decide; never silently repair.
#[test]
fn decreasing_total_variance_pair_is_flagged() {
    let t1 = 7.0 / 365.0;
    let t2 = 28.0 / 365.0;
    let ctx1 = StrikeSliceContext::new(3_000.0, funding_carry(0.04, 0.01), t1);
    let ctx2 = StrikeSliceContext::new(3_000.0, funding_carry(0.04, 0.01), t2);
    let flat = |ctx: &StrikeSliceContext, vol: f64| {
        let f = ctx.forward();
        StrikeQuoteSlice::new(
            (0..9)
                .map(|i| StrikeQuote {
                    strike: f * (-0.4 + 0.8 * f64::from(i) / 8.0).exp(),
                    vol,
                })
                .collect(),
        )
    };
    // w₁ = 0.8²·(7/365) ≈ 0.0123 > w₂ = 0.3²·(28/365) ≈ 0.0069: calendar arb.
    let q1 = flat(&ctx1, 0.8);
    let q2 = flat(&ctx2, 0.3);
    let surface = strike_surface(&[(ctx1, q1), (ctx2, q2)], 1e-4).unwrap();
    let report = surface.arbitrage_report(0.5, 81, 8, 1e-3);
    assert!(
        report.min_calendar_increment < 0.0,
        "crossed total variance must be flagged: {report:?}"
    );
    // The report's increment is per-step of its dense maturity scan (the total
    // ≈ −5.4e-3 decrease spreads over 256 steps ⇒ ≈ −2e-5 per step), so the
    // verdict is read at the step scale…
    assert!(!report.is_arbitrage_free(1e-6), "{report:?}");
    // …and the end-to-end fixed-strike decrease is independently strong: a
    // 2-sample scan measures the whole w(t₂) − w(t₁) drop at the ATM strike.
    let total_drop = surface.term_structure().min_calendar_increment(0.0, 2);
    assert!(
        total_drop < -1e-3,
        "fixed-strike total variance must genuinely decrease: {total_drop}"
    );
}
