//! Pluggable execution strategy contract for algorithmic trading.
//!
//! Enables external quantitative desks to implement proprietary order slicing,
//! reinforcement learning execution agents, or adaptive smart routing strategies
//! without modifying `celnet-algo`'s internal types.

use crate::PeggingStyle;
use crate::AlgoError;

/// Real-time top-of-book market snapshot.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MarketBookSnapshot {
    /// Best bid price.
    pub bid_price: f64,
    /// Best bid available volume.
    pub bid_qty: f64,
    /// Best ask price.
    pub ask_price: f64,
    /// Best ask available volume.
    pub ask_qty: f64,
    /// Consolidated midpoint price: (bid + ask) / 2.
    pub mid_price: f64,
    /// Current consolidated bid-ask spread: ask - bid.
    pub spread: f64,
    /// Imbalance metric: (bid_qty - ask_qty) / (bid_qty + ask_qty).
    pub order_book_imbalance: f64,
}

impl MarketBookSnapshot {
    /// Construct and compute derived midpoint, spread, and imbalance.
    pub fn new(bid_price: f64, bid_qty: f64, ask_price: f64, ask_qty: f64) -> Self {
        let mid_price = 0.5 * (bid_price + ask_price);
        let spread = (ask_price - bid_price).max(0.0);
        let total_vol = bid_qty + ask_qty;
        let order_book_imbalance = if total_vol > 0.0 {
            (bid_qty - ask_qty) / total_vol
        } else {
            0.0
        };
        Self {
            bid_price,
            bid_qty,
            ask_price,
            ask_qty,
            mid_price,
            spread,
            order_book_imbalance,
        }
    }
}

/// Execution slice generated by a pluggable strategy.
#[derive(Debug, Clone, PartialEq)]
pub struct StrategyChildSlice {
    /// Quantity for this slice.
    pub quantity: f64,
    /// Target limit price (None = market order).
    pub limit_price: Option<f64>,
    /// Pegging behavior.
    pub pegging: PeggingStyle,
    /// Intended destination execution venue tag.
    pub target_venue: Option<String>,
}

/// Context provided to the strategy during slice calculation.
#[derive(Debug, Clone)]
pub struct StrategyExecutionContext<'a> {
    /// Total target order quantity.
    pub total_order_qty: f64,
    /// Cumulative executed quantity to date.
    pub executed_qty: f64,
    /// Remaining unexecuted quantity.
    pub remaining_qty: f64,
    /// Elapsed time in seconds since strategy start.
    pub elapsed_seconds: f64,
    /// Total planned execution window in seconds.
    pub total_duration_seconds: f64,
    /// Consolidated order book state.
    pub book: &'a MarketBookSnapshot,
    /// Benchmark historical volume fraction for this time bucket [0.0, 1.0].
    pub historical_volume_fraction: f64,
}

/// Pluggable algorithmic execution strategy trait.
pub trait PluggableExecutionStrategy: Send + Sync {
    /// Stable, unique strategy name identifier (e.g. "ADAPTIVE_SPREAD_SNIPER").
    fn strategy_name(&self) -> &'static str;

    /// Calculate the parameters for the next child slice.
    ///
    /// Returns `Ok(Some(slice))` if a slice should be posted now,
    /// `Ok(None)` if the strategy chooses to wait (e.g. adverse selection back-off),
    /// or [`AlgoError`] on execution parameter violation.
    fn compute_slice(
        &mut self,
        ctx: &StrategyExecutionContext<'_>,
    ) -> Result<Option<StrategyChildSlice>, AlgoError>;

    /// Callback invoked when a child slice fill is confirmed.
    fn on_fill(&mut self, filled_qty: f64, fill_price: f64);
}

/// A reference adaptive spread sniper strategy.
#[derive(Debug, Clone)]
pub struct AdaptiveSpreadStrategy {
    strategy_name: &'static str,
    urgency_factor: f64,
}

impl AdaptiveSpreadStrategy {
    /// Create a new adaptive spread strategy.
    pub fn new(urgency_factor: f64) -> Self {
        Self {
            strategy_name: "ADAPTIVE_SPREAD_SNIPER",
            urgency_factor: urgency_factor.clamp(0.1, 10.0),
        }
    }
}

impl PluggableExecutionStrategy for AdaptiveSpreadStrategy {
    fn strategy_name(&self) -> &'static str {
        self.strategy_name
    }

    fn compute_slice(
        &mut self,
        ctx: &StrategyExecutionContext<'_>,
    ) -> Result<Option<StrategyChildSlice>, AlgoError> {
        if ctx.remaining_qty <= 0.0 {
            return Ok(None);
        }
        let time_progress = (ctx.elapsed_seconds / ctx.total_duration_seconds).clamp(0.0, 1.0);
        let exec_progress = (ctx.executed_qty / ctx.total_order_qty).clamp(0.0, 1.0);

        // If behind schedule, increase participation and peg aggressively
        let behind_schedule = time_progress > exec_progress;
        let slice_qty = (ctx.remaining_qty * 0.1 * self.urgency_factor).min(ctx.remaining_qty);

        let (pegging, limit_price) = if behind_schedule {
            (PeggingStyle::AggressiveSweep, Some(ctx.book.ask_price))
        } else if ctx.book.order_book_imbalance > 0.3 {
            // Strong buy pressure: peg to touch to catch fills
            (PeggingStyle::PassiveTouch, Some(ctx.book.bid_price))
        } else {
            // Neutral: peg to mid
            (PeggingStyle::Midpoint, Some(ctx.book.mid_price))
        };

        Ok(Some(StrategyChildSlice {
            quantity: slice_qty,
            limit_price,
            pegging,
            target_venue: Some("PRIMARY_ECN".to_string()),
        }))
    }

    fn on_fill(&mut self, _filled_qty: f64, _fill_price: f64) {
        // Strategy internal state update
    }
}

/// Factory closure type for instantiating pluggable execution strategies.
pub type StrategyFactory = Box<dyn Fn() -> Box<dyn PluggableExecutionStrategy> + Send + Sync>;

/// Dynamic registry allowing quantitative trading desks to register, replace, and hot-swap
/// execution strategies at runtime without service restarts.
#[derive(Default)]
pub struct StrategyRegistry {
    factories: std::collections::HashMap<String, StrategyFactory>,
}

impl StrategyRegistry {
    /// Create an empty strategy registry.
    pub fn new() -> Self {
        Self {
            factories: std::collections::HashMap::new(),
        }
    }

    /// Create a strategy registry pre-populated with standard house strategies.
    pub fn with_defaults() -> Self {
        let mut reg = Self::new();
        reg.register("ADAPTIVE_SPREAD_SNIPER", || {
            Box::new(AdaptiveSpreadStrategy::new(1.0))
        })
        .expect("unique default strategy");
        reg
    }

    /// Register a strategy factory.
    ///
    /// # Errors
    /// Returns [`AlgoError::InvalidParameter`] if a strategy with the same name is already registered.
    pub fn register<F>(&mut self, name: &str, factory: F) -> Result<(), AlgoError>
    where
        F: Fn() -> Box<dyn PluggableExecutionStrategy> + Send + Sync + 'static,
    {
        if self.factories.contains_key(name) {
            return Err(AlgoError::InvalidParameter(format!(
                "duplicate strategy registration: {name}"
            )));
        }
        self.factories.insert(name.to_string(), Box::new(factory));
        Ok(())
    }

    /// Atomically replace an existing strategy or insert a new one in place.
    pub fn replace_or_insert<F>(&mut self, name: &str, factory: F)
    where
        F: Fn() -> Box<dyn PluggableExecutionStrategy> + Send + Sync + 'static,
    {
        self.factories.insert(name.to_string(), Box::new(factory));
    }

    /// Instantiate a fresh strategy instance by name.
    ///
    /// # Errors
    /// Returns [`AlgoError::InvalidParameter`] if the strategy name is not found in the registry.
    pub fn create_strategy(
        &self,
        name: &str,
    ) -> Result<Box<dyn PluggableExecutionStrategy>, AlgoError> {
        let factory = self
            .factories
            .get(name)
            .ok_or_else(|| AlgoError::InvalidParameter(format!("strategy not found: {name}")))?;
        Ok(factory())
    }

    /// Check if a strategy is registered.
    pub fn has_strategy(&self, name: &str) -> bool {
        self.factories.contains_key(name)
    }

    /// List all registered strategy names.
    pub fn strategy_names(&self) -> Vec<String> {
        let mut names: Vec<String> = self.factories.keys().cloned().collect();
        names.sort();
        names
    }

    /// Number of registered strategies.
    pub fn len(&self) -> usize {
        self.factories.len()
    }

    /// Whether the registry has no strategies registered.
    pub fn is_empty(&self) -> bool {
        self.factories.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_adaptive_spread_strategy() {
        let mut strategy = AdaptiveSpreadStrategy::new(1.0);
        let book = MarketBookSnapshot::new(1.0850, 500_000.0, 1.0852, 400_000.0);
        assert_eq!(strategy.strategy_name(), "ADAPTIVE_SPREAD_SNIPER");

        let ctx = StrategyExecutionContext {
            total_order_qty: 1_000_000.0,
            executed_qty: 200_000.0,
            remaining_qty: 800_000.0,
            elapsed_seconds: 60.0,
            total_duration_seconds: 300.0,
            book: &book,
            historical_volume_fraction: 0.25,
        };

        let slice = strategy.compute_slice(&ctx).unwrap().unwrap();
        assert_eq!(slice.quantity, 80_000.0);
        assert_eq!(slice.pegging, PeggingStyle::Midpoint);
        assert_eq!(slice.limit_price, Some(1.0851));
    }

    #[test]
    fn test_strategy_registry_lifecycle_and_hot_swap() {
        let mut reg = StrategyRegistry::with_defaults();
        assert!(reg.has_strategy("ADAPTIVE_SPREAD_SNIPER"));
        assert_eq!(reg.len(), 1);

        // Duplicate registration rejected
        assert!(reg.register("ADAPTIVE_SPREAD_SNIPER", || {
            Box::new(AdaptiveSpreadStrategy::new(2.0))
        }).is_err());

        // Register custom strategy
        reg.register("CUSTOM_MOMENTUM_SNIPER", || {
            Box::new(AdaptiveSpreadStrategy::new(5.0))
        }).unwrap();
        assert_eq!(reg.len(), 2);
        assert!(reg.has_strategy("CUSTOM_MOMENTUM_SNIPER"));

        // Hot swap / replace in place
        reg.replace_or_insert("CUSTOM_MOMENTUM_SNIPER", || {
            Box::new(AdaptiveSpreadStrategy::new(10.0))
        });
        assert_eq!(reg.len(), 2);

        let instance = reg.create_strategy("CUSTOM_MOMENTUM_SNIPER").unwrap();
        assert_eq!(instance.strategy_name(), "ADAPTIVE_SPREAD_SNIPER");
    }
}
