//! Build-time code generation for the Celnet wire contract.
//!
//! The `.proto` schema is compiled with the **pure-Rust** `protox` compiler — it
//! parses the source into a `FileDescriptorSet` with no dependency on a system
//! `protoc` binary — and that descriptor set is handed to `tonic-build` (driving
//! `prost-build`) to emit both the message types and the gRPC service stubs
//! (client + server). This keeps the build hermetic and reproducible on every
//! platform (CI, containers, Apple Silicon) per the determinism discipline:
//! `skip_protoc_run()` guarantees no `protoc` is ever invoked.
//!
//! ## WS wire-contract manifest (arch item G — `ws-codec-from-proto`)
//!
//! The **same** descriptor set additionally drives a generated `wire_contract`
//! module ([`emit_wire_contract`]): a descriptor-derived manifest of the WS
//! mirror's verb vocabulary (the request/response RPCs and the RFS
//! stream-control oneof arms) plus the message/enum surface. The WebSocket
//! mirror is not a second contract — it is a second *encoding* of this one
//! `celnet.proto` contract — so its routing vocabulary is now sourced from the
//! descriptor rather than a hand-maintained literal that could silently drift
//! from the schema. The manifest is generated deterministically (descriptor
//! declaration order), so the emitted file is byte-identical on every build.

use std::path::PathBuf;

use prost_types::{DescriptorProto, FileDescriptorSet};

fn main() {
    let proto_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("proto");
    let proto_file = proto_dir.join("celnet.proto");

    // Rebuild only when the schema changes.
    println!("cargo:rerun-if-changed={}", proto_file.display());

    // Parse the schema to a FileDescriptorSet with the pure-Rust compiler.
    let file_descriptor_set = protox::compile([&proto_file], [&proto_dir])
        .expect("celnet.proto must compile with protox (no system protoc required)");

    // Generate the WS wire-contract manifest from the descriptor set BEFORE it is
    // moved into tonic-build (`compile_fds` consumes it by value). One descriptor
    // set, two generated artifacts — they cannot diverge.
    emit_wire_contract(&file_descriptor_set);

    // Emit Rust message types AND tonic service stubs from the descriptor set.
    // `skip_protoc_run` keeps the build hermetic — protox already produced the
    // descriptor set, so no `protoc` binary is invoked here either.
    tonic_build::configure()
        .build_client(true)
        .build_server(true)
        .skip_protoc_run()
        .compile_fds(file_descriptor_set)
        .expect("tonic-build must generate message + service stubs from the descriptor set");
}

/// The `ClientStreamMessage` oneof is the RFS stream-control surface — its arm
/// names are exactly the WS `type` discriminators the router classifies as
/// stream-control (forwarded to the live session driver, not the unary edge).
const STREAM_CONTROL_MESSAGE: &str = "ClientStreamMessage";

/// Generate `$OUT_DIR/wire_contract.rs` — the descriptor-derived manifest of the
/// WS mirror's contract surface. Deterministic in descriptor declaration order so
/// the emitted file is byte-identical on every build.
fn emit_wire_contract(fds: &FileDescriptorSet) {
    let mut rpcs: Vec<(String, String, String, String)> = Vec::new();
    let mut stream_control: Vec<String> = Vec::new();
    let mut messages: Vec<String> = Vec::new();
    let mut enums: Vec<String> = Vec::new();

    for file in &fds.file {
        // Services → unary request/response verbs.
        for service in &file.service {
            let svc = service.name();
            for method in &service.method {
                rpcs.push((
                    svc.to_owned(),
                    method.name().to_owned(),
                    last_segment(method.input_type()).to_owned(),
                    last_segment(method.output_type()).to_owned(),
                ));
            }
        }
        // Messages (recursively, incl. nested) → names + the stream-control arms.
        for message in &file.message_type {
            collect_message(message, &mut messages, &mut stream_control);
        }
        // Enums.
        for e in &file.enum_type {
            enums.push(e.name().to_owned());
        }
    }

    let mut out = String::new();
    out.push_str(
        "// @generated by celnet-proto/build.rs from proto/celnet.proto — DO NOT EDIT.\n\
         // The descriptor-derived WS wire-contract manifest (arch item G).\n\n",
    );

    // ---- stream-control verbs (the ClientStreamMessage oneof arm names) -------
    out.push_str(
        "/// The RFS stream-control verbs: the `ClientStreamMessage` oneof arm names\n\
         /// (proto field snake_case), i.e. the exact WS `type` discriminators the\n\
         /// router forwards to the live session driver rather than the unary edge.\n\
         /// Generated from the descriptor, so a new oneof arm is classified with no\n\
         /// hand edit to the router.\n\
         pub const STREAM_CONTROL_VERBS: &[&str] = &[\n",
    );
    for verb in &stream_control {
        out.push_str(&format!("    {verb:?},\n"));
    }
    out.push_str("];\n\n");

    // ---- unary RPC verbs ------------------------------------------------------
    out.push_str(
        "/// One WS request/response RPC, derived from a proto service method: the\n\
         /// service + method names and the request/response message type names. The\n\
         /// descriptor-side source of truth for WS unary-verb coverage.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct WireRpc {\n\
         \x20   /// The proto service the method belongs to (e.g. `PricingService`).\n\
         \x20   pub service: &'static str,\n\
         \x20   /// The proto RPC method name (e.g. `Price`).\n\
         \x20   pub method: &'static str,\n\
         \x20   /// The request message type name (e.g. `PriceRequest`).\n\
         \x20   pub request: &'static str,\n\
         \x20   /// The response message type name (e.g. `PriceResponse`).\n\
         \x20   pub response: &'static str,\n\
         }\n\n\
         /// Every WS request/response RPC, in proto declaration order.\n\
         pub const WIRE_RPCS: &[WireRpc] = &[\n",
    );
    for (svc, method, req, resp) in &rpcs {
        out.push_str(&format!(
            "    WireRpc {{ service: {svc:?}, method: {method:?}, request: {req:?}, response: {resp:?} }},\n"
        ));
    }
    out.push_str("];\n\n");

    // ---- message + enum name surface (coverage / drift guards) ----------------
    out.push_str("/// Every message type name in the contract (incl. nested), in declaration order.\npub const MESSAGES: &[&str] = &[\n");
    for m in &messages {
        out.push_str(&format!("    {m:?},\n"));
    }
    out.push_str("];\n\n");

    out.push_str("/// Every top-level enum type name in the contract, in declaration order.\npub const ENUMS: &[&str] = &[\n");
    for e in &enums {
        out.push_str(&format!("    {e:?},\n"));
    }
    out.push_str("];\n");

    let out_path = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"))
        .join("wire_contract.rs");
    std::fs::write(&out_path, out).expect("write generated wire_contract.rs");
}

/// Collect a message's name (and its nested messages, recursively) and — for the
/// `ClientStreamMessage` — its oneof arm field names (the stream-control verbs).
fn collect_message(
    message: &DescriptorProto,
    messages: &mut Vec<String>,
    stream_control: &mut Vec<String>,
) {
    let name = message.name();
    messages.push(name.to_owned());
    if name == STREAM_CONTROL_MESSAGE {
        for field in &message.field {
            // The control surface is the message's oneof — every arm carries an
            // `oneof_index`. Field names are already proto snake_case == the WS verb.
            if field.oneof_index.is_some() {
                stream_control.push(field.name().to_owned());
            }
        }
    }
    for nested in &message.nested_type {
        collect_message(nested, messages, stream_control);
    }
}

/// The last dotted segment of a fully-qualified proto type (`.celnet.wire.Foo` →
/// `Foo`) — the bare message type name.
fn last_segment(qualified: &str) -> &str {
    qualified.rsplit('.').next().unwrap_or(qualified)
}
